### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by mykola-zomchak** [Kocal/vue-web-extension#643]
I'm fairly new to typescript and bundlers and didn't manage to set up typescript project.
Maybe someone could create an example repo with typescript set up similar to this repo https://github.com/Kocal/vue-web-extension-vue3.

**Comment by Kocal** [comment]
If you use the Vue-CLI 3+ preset, you just have to run `vue add typescript` and it should do the job, see https://cli.vuejs.org/core-plugins/typescript.html#vue-cli-plugin-typescript.

**Comment by mykola-zomchak** [comment]
@Kocal 
Sorry for delay in comments I don't think this is closed. It is not that simple to setup typescript. Here is what I thied:

```
hacker69@hacker69-TM1701:~/noty$ vue create --preset kocal/vue-web-extension typescript extension

 Info: You provided more than one argument. The first one will be used as the app's name, the rest are ignored.
Fetching remote preset kocal/vue-web-extension...


Vue CLI v4.5.8
✨  Creating project in /home/hacker69/noty/typescript.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.


success Saved lockfile.
Done in 15.24s.
🚀  Invoking generators...

@vue/cli-plugin-eslint
? Pick an ESLint config: Basic
? Pick additional lint features: Lint on save

vue-cli-plugin-browser-extension
? Which browser extension components do you wish to generate? background, popup, options, content scripts, standalone
? Generate a new signing key (danger)? No

Preset options:
? Install axios? Yes
📦  Installing additional dependencies...

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 6.21s.
⚓  Running completion hooks...
error: 'request' is defined but never used (no-unused-vars) at typescript/src/background.js:1:49:
> 1 | browser.runtime.onMessage.addListener(function (request, sender, sendResponse) {
    |                                                 ^
  2 |   console.log('Hello from the background')
  3 | 
  4 |   browser.tabs.executeScript({


error: 'sender' is defined but never used (no-unused-vars) at typescript/src/background.js:1:58:
> 1 | browser.runtime.onMessage.addListener(function (request, sender, sendResponse) {
    |                                                          ^
  2 |   console.log('Hello from the background')
  3 | 
  4 |   browser.tabs.executeScript({


error: 'sendResponse' is defined but never used (no-unused-vars) at typescript/src/background.js:1:66:
> 1 | browser.runtime.onMessage.addListener(function (request, sender, sendResponse) {
    |                                                                  ^
  2 |   console.log('Hello from the background')
  3 | 
  4 |   browser.tabs.executeScript({


3 errors found.
hacker69@hacker69-TM1701:~/noty$ code typescript/

hacker69@hacker69-TM1701:~/noty/typescript$ vue add typescript
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing @vue/cli-plugin-typescript...

yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 18 new dependencies.
info Direct dependencies
└─ @vue/cli-plugin-typescript@4.5.8
info All dependencies
├─ @types/parse-json@4.0.0
├─ @types/webpack-env@1.15.3
├─ @vue/cli-plugin-typescript@4.5.8
├─ at-least-node@1.0.0
├─ babel-code-frame@6.26.0
├─ builtin-modules@1.1.1
├─ diff@4.0.2
├─ fork-ts-checker-webpack-plugin-v5@5.2.1
├─ fork-ts-checker-webpack-plugin@3.1.1
├─ fs-monkey@1.0.1
├─ js-tokens@3.0.2
├─ memfs@3.2.0
├─ microevent.ts@0.1.1
├─ ts-loader@6.2.2
├─ tslint@5.20.1
├─ tsutils@2.29.0
├─ worker-rpc@0.1.1
└─ yaml@1.10.0
Done in 3.79s.
✔  Successfully installed plugin: @vue/cli-plugin-typescript

? Use class-style component syntax? Yes
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Convert all .js files to .ts? Yes
? Allow .js files to be compiled? No
? Skip type checking of all declaration files (recommended for apps)? Yes

🚀  Invoking generator for @vue/cli-plugin-typescript...
📦  Installing additional dependencies...

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 6.30s.
⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: @vue/cli-plugin-typescript
hacker69@hacker69-TM1701:~/noty/typescript$ yarn serve
yarn run v1.22.10
$ vue-cli-service build --mode development --watch

⠙  Building for development...[ Starting the Hot Extension Reload Server... ]
Starting type checking service...
Using 1 worker with 2048MB memory limit
⠼  Building for development... WARN  No key.pem file found. This is fine for dev, however you may have problems publishing without one


 ERROR  Failed to compile with 5 errors                                                                                                                                                       10:56:32 AM

These dependencies were not found:

* /home/hacker69/noty/typescript/src/background.js in multi ./src/background.js
* /home/hacker69/noty/typescript/src/content-scripts/content-script.js in multi ./src/content-scripts/content-script.js
* /home/hacker69/noty/typescript/src/options/main.js in multi ./src/options/main.js
* /home/hacker69/noty/typescript/src/popup/main.js in multi ./src/popup/main.js
* /home/hacker69/noty/typescript/src/standalone/main.js in multi ./src/standalone/main.js

To install them, you can run: npm install --save /home/hacker69/noty/typescript/src/background.js /home/hacker69/noty/typescript/src/content-scripts/content-script.js /home/hacker69/noty/typescript/src/options/main.js /home/hacker69/noty/typescript/src/popup/main.js /home/hacker69/noty/typescript/src/standalone/main.js
Type checking in progress...
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Kocal** [comment]
Well, yes you have to type some variables to prevent compilation issues.
For any features request, you can open an issue on https://github.com/adambullmer/vue-cli-plugin-browser-extension (which is the plugin that this preset use).

**Comment by mykola-zomchak** [comment]
Ok, so if i manage to set it up I'd like to make a pull request with instructions on how to set it up with typescript, should I edit this repo Readme or the plugin repo?

**Comment by Kocal** [comment]
That's would be welcomed!
You can create new document page in https://github.com/Kocal/vue-web-extension/tree/master/docs/development which will be rendered on https://vue-web-extension.netlify.app/.

**Comment by djob** [comment]
Anybody got a eslint-loader error on .ts files?
```
Module parse failed: Unexpected token (2:8)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js

```

how to disable eslinter on .ts files?
