### ISSUE TITLE
Cannot serve and build

### ISSUE THREAD

**Issue by ckissi** [Kocal/vue-web-extension#683]
I cannot build , even npm run serve doesn't  work

**To Reproduce**
npm run build

```
 ERROR  TypeError: Cannot read property 'ignore' of undefined
TypeError: Cannot read property 'ignore' of undefined
    at /Users/csabakissi/ChromeExt/my-extension/node_modules/vue-cli-plugin-browser-extension/index.js:129:20
    at Object.tap (/Users/csabakissi/ChromeExt/my-extension/node_modules/webpack-chain/src/Plugin.js:30:24)
    at /Users/csabakissi/ChromeExt/my-extension/node_modules/vue-cli-plugin-browser-extension/index.js:128:36
    at /Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (/Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/commands/build/index.js:77:13
    at Service.run (/Users/csabakissi/ChromeExt/my-extension/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
**Screenshots**

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: 2.0
 - OS:  MacOS Monterey
 - Node.js version: 14.17

Tried on second computer with the same result.

**Comment by choxner** [comment]
In `package.json` you can change `"vue-cli-plugin-browser-extension": "latest"` to `"vue-cli-plugin-browser-extension": "npm:@rhilip/vue-cli-plugin-browser-extension@^0.26.0"`. Then remove your `node_modules` folder and run `npm i` to reinstall. Had the same issue and this resolved it for me.
