### ISSUE TITLE
Unable to compile or run

### ISSUE THREAD

**Issue by webjosn** [Kocal/vue-web-extension#685]
Cannot read properties of undefined (reading 'ignore')
    at E:\free丶苏\code-project\chrome-extension_v3\node_modules\vue-cli-plugin-browser-extension\index.js:129:24
    at Object.tap (E:\free丶苏\code-project\chrome-extension_v3\node_modules\webpack-chain\src\Plugin.js:30:24)
    at E:\free丶苏\code-project\chrome-extension_v3\node_modules\vue-cli-plugin-browser-extension\index.js:128:38
    at E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\PluginAPI.js:145:25)
    at module.exports (E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:9:22)
    at build (E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\commands\build\index.js:147:50)
    at E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\commands\build\index.js:69:13
    at Service.run (E:\free丶苏\code-project\chrome-extension_v3\node_modules\@vue\cli-service\lib\Service.js:262:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yonghi** [comment]
一样的问题，不知道您解决了吗

**Comment by WillTang2018** [comment]
me too

**Comment by yonghi** [comment]
you can just change to another project,which is https://github.com/sanyu1225/vue-cli-plugin-chrome-extension-cli

**Comment by ManutdGTA** [comment]
me too

**Comment by oopty** [comment]
i found this [issue](https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/126)
the solution in issue is that below
```
"vue-cli-plugin-browser-extension": "npm:@rhilip/vue-cli-plugin-browser-extension@^0.27.0",
```

**Comment by vongrra** [comment]
> "vue-cli-plugin-browser-extension": "npm:@rhilip/vue-cli-plugin-browser-extension@^0.27.0",

this doesn't help. I am getting the same error :
` ERROR  TypeError: Cannot read properties of undefined (reading 'ignore')
TypeError: Cannot read properties of undefined (reading 'ignore')
    at /Users/i304143/OneDrive/Pinalist_2/my-extension/node_modules/vue-cli-plugin-browser-extension/index.js:129:20
    at Object.tap (/Users/i304143/OneDrive/Pinalist_2/my-extension/node_modules/webpack-chain/src/Plugin.js:30:24)`

Please look at it. Many Thanks
